version: '3'
services:
  spark-master:
    image: bde2020/spark-master:3.1.2-hadoop3.2
    container_name: spark-master
    hostname: spark_master
    user: root
    ports:
      - "8080:8080"
      # - "7077:7077"
      # - "4132:4040"
    # environment:
    #   - INIT_DAEMON_STEP=setup_spark
    #   - SPARK_MASTER_HOST=172.18.0.2
    #   - SPARK_MASTER_PORT=7077
    volumes:
      - ./:/project
    networks:
      datapipeline:
        ipv4_address: 172.18.0.2
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      datapipeline:
        ipv4_address: 172.18.0.6
  kafka:
    image: 'bitnami/kafka:3.1'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.7:9092
      - KAFKA_ADVERTISED_HOST_NAME=172.18.0.7
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="topic1:5:1,topic2:5:1"
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - ./:/project
    networks:
      datapipeline:
        ipv4_address: 172.18.0.7
  cassandra:
    image: 'bitnami/cassandra:4.0.4'
    container_name: cassandra
    hostname: cassandra
    ports:
      - '9042:9042'
    volumes:
      - ./:/project
    networks:
      datapipeline:
        ipv4_address: 172.18.0.8
networks:
    datapipeline:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.18.0.0/16"