version: '3'
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper
    hostname: zookeeper
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      datapipeline:
        ipv4_address: 172.18.0.6
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka
    hostname: kafka
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://172.18.0.7:9092
      - KAFKA_ADVERTISED_HOST_NAME=172.18.0.7
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CREATE_TOPICS="topic1:1:1"
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true
    depends_on:
      - zookeeper
    volumes:
      - ./:/project
    networks:
      datapipeline:
        ipv4_address: 172.18.0.7
  url_generator:
    image: openjdk:17
    container_name: url_generator
    ports:
      - '5050:5050'
    volumes:
      - "./url_generator/url_generator/target/SpringTest-1.0-SNAPSHOT.jar"
    command: ['java', '-jar', '/SpringTest-1.0-SNAPSHOT.jar']
    networks:
      datapipeline:
        ipv4_address: 172.18.0.8
  url_counter:
    image: openjdk:17
    container_name: url_counter
    ports:
      - '5060:5060'
    volumes:
      - "./url_counter/url_counter/target/SpringTest-1.0-SNAPSHOT.jar"
    command: ['java', '-jar', '/SpringTest-1.0-SNAPSHOT.jar']
    networks:
      datapipeline:
        ipv4_address: 172.18.0.9
networks:
    datapipeline:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: "172.10.0.0/16"